# Generated by Django 3.2.12 on 2023-02-24 15:16
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("trainer", "name")},
        ),
    ]
