# Generated by Django 3.2.12 on 2023-02-24 14:21
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "__first__"),
        ("pokemon", "0003_alter_pokemon_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="team.team",
            ),
        ),
    ]
