# Generated by Django 3.2.12 on 2023-02-27 14:46
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pokemon", "0004_pokemon_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pokemons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
