# Generated by Django 3.2.12 on 2023-02-27 14:53
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_alter_team_unique_together"),
        ("pokemon", "0005_alter_pokemon_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="team.team",
            ),
        ),
    ]
